apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: 145054867171.dkr.ecr.us-east-1.amazonaws.com/wallace-hatch-backend:V_68
        ports:
        - name: backend-port
          containerPort: 8090
        resources:
            requests:
              cpu: 10m
        env:
          - name: MAILCHIMP_API
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MAILCHIMP_API
          - name: STRIPE_KEY
            valueFrom:
              secretKeyRef:
                name: secrets
                key: STRIPE_LIVE_KEY
          - name: STRIPE_WEBHOOK_SIG
            valueFrom:
              secretKeyRef:
                name: secrets
                key: STRIPE_WEBHOOK_SIG
          - name: MAILGUN_API_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MAILGUN_API_SECRET_KEY
          - name: MAILGUN_API_PUBlIC_KEY
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MAILGUN_API_PUBlIC_KEY
          - name: EASY_POST_KEY
            valueFrom:
              secretKeyRef:
                name: secrets
                key: EASY_POST_LIVE_KEY
          - name: TWILIO_ACCOUNT_SID
            valueFrom:
              secretKeyRef:
                name: secrets
                key: TWILIO_LIVE_ACCOUNT_SID
          - name: TWILIO_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: secrets
                key: TWILIO_LIVE_AUTH_TOKEN
          - name: TWILIO_PHONE_NUMBER
            valueFrom:
              secretKeyRef:
                name: secrets
                key: TWILIO_PHONE_NUMBER
          - name: GOOGLE_URL_API
            valueFrom:
              secretKeyRef:
                name: secrets
                key: GOOGLE_URL_API
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MONGODB_URI
          - name: MONGODB_NAME
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MONGODB_NAME
---


apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: backend-port
  type: NodePort
