apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: api
    spec: 
      containers:
      - name: api-container
        image: 896897385194.dkr.ecr.us-east-2.amazonaws.com/api-production:latest
        ports: 
        - name: api-port
          containerPort: 8080
        env: 
          - name: NATS_SERVER
            value: nats://nats:4222
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MONGODB_URI
          - name: MONGODB_NAME
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MONGODB_NAME
          - name: CMS_MONGODB_NAME
            valueFrom:
              secretKeyRef:
                name: secrets
                key: CMS_MONGODB_NAME
          - name: MONGODB_COLL
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MONGODB_COLL
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: secrets
                key: PORT

          - name: AUTH0_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: secrets
                key: AUTH0_CLIENT_SECRET
          - name: AUTH0_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: secrets
                key: AUTH0_CLIENT_ID
          - name: AUTH0_CLIENT_AUDIENCE
            valueFrom:
              secretKeyRef:
                name: secrets
                key: AUTH0_CLIENT_AUDIENCE
          - name: PLAID_SECRET
            valueFrom:
              secretKeyRef:
                name: secrets
                key: PLAID_SECRET
          - name: PLAID_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: secrets
                key: PLAID_CLIENT_ID
          - name: PLAID_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: secrets
                key: PLAID_PUBLIC_KEY
          - name: PLAID_ENV
            valueFrom:
              secretKeyRef:
                name: secrets
                key: PLAID_ENV
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MONGODB_URI
          - name: CMS_MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: secrets
                key: CMS_MONGODB_URI


---


apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: api-port
  type: NodePort
