apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend-deployment-staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-staging
    spec:
      containers:
      - name: backend-container-staging
        image: 145054867171.dkr.ecr.us-east-1.amazonaws.com/wallace-hatch-backend-staging:V_40
        ports:
        - name: backend-port
          containerPort: 8090
        resources:
            requests:
              cpu: 10m
        env:
          - name: MAILCHIMP_API
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MAILCHIMP_API
          - name: STRIPE_KEY
            valueFrom:
              secretKeyRef:
                name: secrets
                key: STRIPE_TEST_KEY
          - name: STRIPE_WEBHOOK_SIG
            valueFrom:
              secretKeyRef:
                name: secrets
                key: STRIPE_WEBHOOK_SIG
          - name: MAILGUN_API_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MAILGUN_API_SECRET_KEY
          - name: MAILGUN_API_PUBlIC_KEY
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MAILGUN_API_PUBlIC_KEY
          - name: EASY_POST_KEY
            valueFrom:
              secretKeyRef:
                name: secrets
                key: EASY_POST_TEST_KEY
          - name: TWILIO_ACCOUNT_SID
            valueFrom:
              secretKeyRef:
                name: secrets
                key: TWILIO_TEST_ACCOUNT_SID
          - name: TWILIO_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: secrets
                key: TWILIO_TEST_AUTH_TOKEN
          - name: TWILIO_PHONE_NUMBER
            valueFrom:
              secretKeyRef:
                name: secrets
                key: TWILIO_TEST_PHONE_NUMBER


---


apiVersion: v1
kind: Service
metadata:
  name: backend-service-staging
spec:
  selector:
    app: backend-staging
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: backend-port
  type: NodePort
