# frontend staging autoscaler
apiVersion: v1
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: frontend-deployment-staging
    namespace: default
  spec:
    maxReplicas: 1
    minReplicas: 1
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: frontend-deployment-staging
    targetCPUUtilizationPercentage: 50
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""


---
# frontend autoscaler
apiVersion: v1
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: frontend-deployment
    namespace: default
  spec:
    maxReplicas: 5
    minReplicas: 1
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: frontend-deployment
    targetCPUUtilizationPercentage: 50
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""

---
# backend staging autoscaler
apiVersion: v1
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: backend-deployment-staging
    namespace: default
  spec:
    maxReplicas: 5
    minReplicas: 1
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: backend-deployment-staging
    targetCPUUtilizationPercentage: 50
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""


---
# backend autoscaler
apiVersion: v1
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: backend-deployment
    namespace: default
  spec:
    maxReplicas: 5
    minReplicas: 1
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: backend-deployment
    targetCPUUtilizationPercentage: 50
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
