---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: askvest.com
    http:
      paths:
      - path: /
        backend:
            serviceName: client-service
            servicePort: 80
  - host: www.askvest.com
    http:
      paths:
      - path: /
        backend:
            serviceName: client-service
            servicePort: 80

  - host: api-staging.askvest.com
    http:
      paths:
      - path: /
        backend:
            serviceName: api-service
            servicePort: 80
